version: '3.8'

volumes:
  db-data:

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    container_name: 'db'
  porxy:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: 'proxy'
    env_file:
      - ./.env
    ports:
      - "3000:3000"